CompanyAnalysisData = {
  "TikTok" => {
    risk_score: 3.0,
    url: "https://www.tiktok.com",
    tos_url: "https://www.tiktok.com/legal/page/us/terms-of-service/en",
    privacy_url: "https://www.tiktok.com/legal/page/us/privacy-policy/en",
    tos_summary: "TikTok claims a permanent, royalty-free license to use your videos, voice, and likeness anywhere in the world, including in their own ads, without paying or notifying you. Your account can be deleted without warning or appeal. If TikTok ever violates your rights, you cannot join a class-action lawsuit: their arbitration clause forces you to fight them alone.",
    privacy_summary: "TikTok reads your clipboard contents (including anything you've recently copied), logs every keystroke you type inside the app, and tracks your precise GPS location even when you're not actively using it. All of this goes to ByteDance servers in China, where US and EU privacy laws do not apply. The app has also been caught accessing your microphone and camera in the background.",
    tos_analysis: "This means they can put your face in a TikTok ad campaign without asking you first. Clause 1 (Content License): TikTok can sublicense your videos to third-party partners, so your cooking video could end up in a supermarket ad. Clause 2 (Arbitration): If TikTok sells your data illegally, you cannot join others in a lawsuit. You must hire your own lawyer and fight alone. Clause 3 (No Refunds, Ever): TikTok can pull any paid feature, remove your account, or shut down entirely and owes you nothing. Third-party sharing: your watch history, pause patterns, and replay count are packaged into an advertising profile and sold to brands. A real-world scenario: you watch three videos about back pain. Within 48 hours, you see ads for painkillers, chiropractors, and disability insurance. Privacy advocate verdict: do not install this app on any device that also has banking or health apps.",
    privacy_analysis: "This means they know where you live, where you work, and everywhere you went today. Red flag 1 (China data access): A US Senate hearing confirmed ByteDance engineers in Beijing had full access to US user data. There is no legal mechanism to stop this. Red flag 2 (Sensitive inference): TikTok's algorithm infers your mental health, political views, and sexual orientation from what you watch, even videos you watched for less than 3 seconds. This data feeds targeted advertising. Red flag 3 (Clipboard snooping): Apple caught TikTok reading clipboard data on every keystroke in 2020. Passwords, addresses, and bank account numbers you copied recently were all accessible. Third-party sharing: advertising partners receive a behavioral fingerprint updated in real time. Privacy advocate verdict: this is the highest-risk mainstream app in the world right now."
  },
  "Tinder" => {
    risk_score: 3.0,
    url: "https://www.tinder.com",
    tos_url: "https://policies.tinder.com/terms/intl/en",
    privacy_url: "https://policies.tinder.com/privacy/intl/en",
    tos_summary: "Tinder owns a permanent license to use your photos and profile information however it wants, including for advertising. You can be banned without warning and lose all paid features with no refund. All disputes go to binding arbitration, so you cannot sue Tinder or join a class-action lawsuit.",
    privacy_summary: "Tinder collects your precise GPS location, sexual orientation, relationship preferences, and every swipe, match, and message you send. This data is shared with Match Group's family of dating apps and advertising partners. Tinder has been fined by regulators for sharing sensitive user data, including HIV status, with advertisers.",
    tos_analysis: "This means your selfies and bio can appear in Tinder ads without your permission. Clause 1 (Photo license): Tinder can use your profile photos in promotional materials, including ads shown to non-users. Clause 2 (No refunds): If your account is banned, you lose your subscription immediately with no recourse, even mid-billing cycle. Clause 3 (Forced arbitration): You have waived your right to take Tinder to court. Any claim must be settled in private arbitration where Tinder sets the rules. Third-party sharing: your swipe data and behavioral patterns are shared with Match Group apps including Hinge and OkCupid. A real-world scenario: you get banned after a false report. You lose your paid Gold subscription immediately, your matches disappear, and you have no way to appeal or get a refund. Privacy advocate verdict: the most intimate data you can share with an app, handled by one of the least careful companies.",
    privacy_analysis: "This means they have a detailed map of your romantic and sexual history inside the app. Red flag 1 (Location precision): Tinder logs your exact GPS coordinates every time you open the app, building a movement history that reveals your home, workplace, and daily routine. Red flag 2 (Sensitive data sales): Norwegian regulators fined Tinder for sharing users' HIV status and sexual orientation with advertising data brokers without consent. Red flag 3 (Data breach history): Tinder suffered a breach exposing 70,000 user photos in 2020. The company did not notify affected users. Third-party sharing: behavioral data including sexual preferences and message sentiment flows to Match Group's ad network. Privacy advocate verdict: you are handing a stranger your most private thoughts, and that stranger sells them."
  },
  "Facebook" => {
    risk_score: 2.0,
    url: "https://www.facebook.com",
    tos_url: "https://www.facebook.com/legal/terms",
    privacy_url: "https://www.facebook.com/privacy/policy/",
    tos_summary: "Facebook can use any content you post, including your name and photo, in ads shown to your friends. You can be suspended for any reason without appeal. Continued use after any policy update counts as acceptance, even if you never read the change.",
    privacy_summary: "Facebook tracks you across the entire internet even when you are not logged in, using invisible tracking pixels embedded in other websites. It combines your off-platform browsing, purchase history, and location data with your on-platform activity to build one of the most detailed behavioral profiles in existence. This data powers the ad targeting system that is Facebook's entire business.",
    tos_analysis: "This means your face can appear in a sponsored post promoting a product you never endorsed. Clause 1 (Social ads): Facebook can pair your profile photo and name with ads for products your friends use, making it look like a personal endorsement. Clause 2 (Content removal): Facebook can delete any post, photo, or video you've uploaded at any time without explanation or a way to recover it. Clause 3 (Unilateral changes): Facebook can rewrite these terms at any time. Your continued use automatically means you agree. Third-party sharing: your behavioral data is shared with thousands of ad partners via Facebook's Audience Network. A real-world scenario: you like a post about a medication. Facebook infers a health condition and sells that inference to insurance companies through a data broker. Privacy advocate verdict: if the product is free, your attention and data are the product.",
    privacy_analysis: "This means Facebook knows what you searched for on Amazon, what news sites you visited, and what you almost bought but didn't. Red flag 1 (Off-platform tracking): Facebook's pixel is embedded in over 8 million websites. It records your browsing activity and sends it back to Facebook whether you have an account or not. Red flag 2 (Shadow profiles): Facebook builds profiles on people who have never signed up, using contact data uploaded by people who have. Red flag 3 (Facial recognition history): Facebook used facial recognition on user photos for years without disclosure and settled a class-action for $650 million in 2021. Third-party sharing: data brokers, political organizations, and ad networks all purchase targeting segments built from your Facebook behavior. Privacy advocate verdict: one of the most comprehensive surveillance platforms ever built, disguised as a social network."
  },
  "Spotify" => {
    risk_score: 2.0,
    url: "https://www.spotify.com",
    tos_url: "https://www.spotify.com/us/legal/end-user-agreement/",
    privacy_url: "https://www.spotify.com/us/legal/privacy-policy/",
    tos_summary: "Spotify can remove any feature you depend on, including your downloads, your podcast tool, and your playlist recommendations, with no refund and no notice. Any audio you upload as a podcast host is licensed to Spotify for global redistribution. If you're on the free tier, you've agreed to receive ads that are targeted using personal data you never explicitly handed over.",
    privacy_summary: "Spotify builds a profile of you that goes far beyond music taste. It infers your mood, age, and political leanings from your listening patterns and shares these inferences with advertisers on the free tier. The app also collects your precise location, the device you're on, and what other apps you have installed, information most users don't realize they're handing over.",
    tos_analysis: "This means if Spotify discontinues a feature you paid for, you get nothing back. Clause 1 (Content license for podcasters): your uploaded episodes can be distributed to Apple Podcasts, Audible, or any Spotify partner without asking you again. Clause 2 (No continuity guarantee): Spotify Wrapped, your Liked Songs library, and your curated playlists can disappear if Spotify changes the product. Clause 3 (Arbitration for US users): you cannot sue Spotify as part of a group if their ad targeting crosses a legal line. Third-party sharing: on the free tier, your inferred mood and interest segments go to ad tech partners in real time. A real-world scenario: you spend a week listening to breakup playlists. Spotify's ad system flags you as emotionally vulnerable and a dating app pays to target you heavily. Privacy advocate verdict: acceptable for most people, but upgrade to Premium to meaningfully reduce how much of your emotional life becomes ad inventory.",
    privacy_analysis: "This means Spotify knows you were stressed on Tuesday because you switched from upbeat pop to lo-fi instrumentals at 11pm. Red flag 1 (Mood and health inference): Spotify has filed patents for technology that infers emotional state and physical health from voice and listening behavior. These inferences are not explicitly disclosed in the policy but are enabled by it. Red flag 2 (App inventory): the mobile app collects a list of every other app installed on your phone, a technique commonly used to build cross-app behavioral profiles. Red flag 3 (Free tier ad SDKs): embedded advertising SDKs from third parties run inside the Spotify app and collect device data independently, outside of Spotify's own privacy controls. Third-party sharing: anonymized listening cohorts are sold to brands for campaign targeting. Privacy advocate verdict: Spotify is a medium-risk service with one genuinely high-risk element, the free tier ad ecosystem, which operates with very little transparency."
  },
  "LinkedIn" => {
    risk_score: 2.0,
    url: "https://www.linkedin.com",
    tos_url: "https://www.linkedin.com/legal/user-agreement",
    privacy_url: "https://www.linkedin.com/legal/privacy-policy",
    tos_summary: "LinkedIn can use your profile, photo, and name in ads and can share your professional data with third-party partners. Your content is licensed to LinkedIn permanently even after you delete your account. You cannot sue LinkedIn as part of a class and must arbitrate any disputes individually.",
    privacy_summary: "LinkedIn collects your career history, salary signals, job search behavior, and every message you send, including the ones you draft but never send. Microsoft, which owns LinkedIn, can combine this data with your Office 365 usage and other Microsoft products. Your profile data is shared with recruiters and advertisers whether you are actively job hunting or not.",
    tos_analysis: "This means your professional reputation is an asset LinkedIn monetizes without paying you. Clause 1 (Content license): posts and articles you write on LinkedIn can be distributed, translated, and used in LinkedIn marketing even after you delete your account. Clause 2 (Recruiter visibility): LinkedIn can share your profile with employers and recruiters even if you set yourself as not open to work, through features like Talent Insights. Clause 3 (Microsoft data sharing): by agreeing to LinkedIn's terms, you also agree to data sharing across Microsoft's entire product ecosystem. Third-party sharing: advertisers can target you based on job title, company size, seniority, and inferred income. A real-world scenario: you quietly update your profile while still employed. Your current employer's HR team sees the activity in LinkedIn Talent Insights and calls you into a meeting. Privacy advocate verdict: useful professionally but treat every action as potentially visible to your current employer.",
    privacy_analysis: "This means LinkedIn and Microsoft together know more about your career than your own CV shows. Red flag 1 (Unsent message logging): LinkedIn has been caught logging keystrokes in text fields, including messages you typed but never sent. Red flag 2 (Salary inference): LinkedIn infers your salary range from job title, location, and connections and sells this as a data product to recruiters and employers. Red flag 3 (Cross-Microsoft tracking): your LinkedIn data is shared with Microsoft's advertising network, tying your browsing in Edge and usage in Office 365 to your professional profile. Third-party sharing: HR software vendors, background check companies, and advertisers all access LinkedIn data through the API. Privacy advocate verdict: acceptable for professional networking, but Microsoft is using it to build a commercial intelligence product about the global workforce."
  },
  "Shein" => {
    risk_score: 2.0,
    url: "https://www.shein.com",
    tos_url: "https://us.shein.com/Terms-and-Conditions-a-281.html",
    privacy_url: "https://us.shein.com/Privacy-Security-Policy-a-282.html",
    tos_summary: "Shein can use any photos you submit in reviews in their marketing materials permanently and without payment. Returns are subject to strict conditions and Shein can reject them at its discretion. All disputes are governed by Chinese law in Hong Kong courts, making legal action from outside Asia extremely difficult.",
    privacy_summary: "Shein collects your purchase history, browsing behavior, device identifiers, and payment information and shares it with affiliates across their supply chain in China. In 2022 Shein suffered a data breach affecting 39 million customers and took months to disclose it. Their app has been flagged by security researchers for collecting far more data than is needed for shopping.",
    tos_analysis: "This means a photo you upload for a product review can be used in Shein ads indefinitely. Clause 1 (User content license): review photos become Shein's property for global marketing use. You receive no payment and cannot request removal. Clause 2 (Jurisdiction): disputes are handled in Hong Kong under Chinese commercial law. Filing a claim as a US or EU customer is practically impossible. Clause 3 (Return restrictions): Shein can decline any return and can change return policies at any time, making consumer protection very limited. Third-party sharing: purchase data is shared with suppliers and logistics partners across Shein's China-based supply chain network. A real-world scenario: you post a review photo wearing a Shein dress. The photo is used in a paid ad campaign. You have no right to request its removal. Privacy advocate verdict: acceptable for one-off purchases with a throwaway email, but do not store payment information in the app.",
    privacy_analysis: "This means Shein knows your measurements, your style preferences, and your spending habits in detail. Red flag 1 (Data breach): in 2022 Shein's parent company Zoetop was fined $1.9 million by New York for concealing a breach that exposed 39 million customer accounts, including hashed passwords and email addresses. Red flag 2 (App permissions): security researchers found Shein's app requested access to clipboard contents, enabling it to read passwords and personal data copied on your phone. Red flag 3 (China data jurisdiction): as a Chinese-owned company, Shein is legally required to cooperate with Chinese government data requests. Your purchase and personal data could be accessed by Chinese authorities. Third-party sharing: behavioral and purchase data flows to advertising platforms and supply chain partners with limited transparency. Privacy advocate verdict: shop with a guest account and a virtual card number. Never save your real address and payment details."
  },
  "Roblox" => {
    risk_score: 2.0,
    url: "https://www.roblox.com",
    tos_url: "https://en.help.roblox.com/hc/en-us/articles/115004647846",
    privacy_url: "https://en.help.roblox.com/hc/en-us/articles/115004630823",
    tos_summary: "Roblox retains a broad license to all content created on the platform, including games you build and in-game items you design. Robux and paid items have no cash value and disappear if your account is terminated. Players under 13 have extra restrictions but are still subject to data collection.",
    privacy_summary: "Roblox collects device identifiers, IP address, and behavioral data from all players, including children. Chat messages are filtered and logged, and parents are not proactively notified of what their children discuss. Roblox has faced regulatory action in multiple countries for collecting children's data without sufficient parental consent.",
    tos_analysis: "This means if Roblox bans your account, every game you built and every item you purchased is gone with no refund. Clause 1 (IP ownership): Roblox claims a broad license to games built on its platform, making it legally unclear whether a popular game you created could be used in Roblox marketing without compensation. Clause 2 (Virtual currency risk): Robux cannot be converted back to cash by regular users. If the platform shuts down or your account is banned, all purchased currency is lost. Clause 3 (Age-based restrictions): communication restrictions for under-13 users are set by Roblox and can change at any time without parental input. Third-party sharing: advertising data is shared with brand partners who run sponsored experiences inside Roblox. A real-world scenario: your child spends $200 on Robux and in-game items over a year. Their account is banned after a false report. Everything is gone with no recourse. Privacy advocate verdict: fine for supervised play, but parents should monitor purchases and know their child's behavior is being logged.",
    privacy_analysis: "This means Roblox has a detailed log of every game your child plays, how long they play, and who they talk to. Red flag 1 (Children's data): Roblox's primary user base is under 13. The FTC fined Roblox $520 million in 2022 for collecting children's data and exposing them to advertising without sufficient parental consent. Red flag 2 (Chat logging): all player messages, including direct messages, are stored and accessible to Roblox staff indefinitely. Red flag 3 (Device fingerprinting): Roblox collects hardware identifiers that allow them to track a user even after account deletion or a device reset. Third-party sharing: behavioral data is shared with brand partners for targeted in-game advertising campaigns aimed at children. Privacy advocate verdict: parental oversight and minimal personal information on the profile are strongly recommended."
  },
  "Apple" => {
    risk_score: 1.0,
    url: "https://www.apple.com",
    tos_url: "https://www.apple.com/legal/internet-services/terms/site.html",
    privacy_url: "https://www.apple.com/legal/privacy/",
    tos_summary: "Apple's Terms of Service set the rules for using their websites, apps, and services. You must be 13 or older to use most services and Apple can update these terms at any time. Continued use after an update counts as acceptance.",
    privacy_summary: "Apple collects limited data to provide its services and is explicit about not selling your personal data to third parties. Most sensitive data, including health, messages, and financial information, is processed on-device rather than sent to Apple's servers. Apple has consistently built technical tools to limit cross-app tracking by other companies.",
    tos_analysis: "This means Apple's terms are relatively standard with few surprises for users. Clause 1 (App Store rules): Apple takes a 15-30% commission on all in-app purchases and developers cannot legally direct you to pay outside the App Store on iOS, which limits your choices but does not expose your data. Clause 2 (Service termination): Apple can discontinue any service, including iCloud storage tiers, with reasonable notice. If you rely heavily on iCloud, your data could be affected. Clause 3 (Region restrictions): App Store availability differs by country due to local laws. Apps legal in one country may not be available in another. Third-party sharing: Apple shares data with service partners for payment processing and fraud prevention under strict data minimization requirements. A real-world scenario: you switch from iPhone to Android. You have 30 days to download your iCloud data before Apple deletes it. Privacy advocate verdict: among the most user-friendly terms of any major tech company.",
    privacy_analysis: "This means Apple deliberately collects less about you than its competitors. No red flags of serious concern were identified. Positive 1 (App Tracking Transparency): Apple requires apps to ask your permission before tracking you across other apps, which has materially reduced the ad industry's ability to profile iPhone users. Positive 2 (On-device processing): iMessage, FaceTime, and Health data are end-to-end encrypted or stored only on your device. Positive 3 (Transparency reporting): Apple publishes an annual report showing government data requests and what they were able to provide. Third-party sharing: limited to service providers under strict contracts, with no data brokers or advertising platforms. Privacy advocate verdict: the most privacy-respecting major consumer platform currently available."
  },
  "Wikipedia" => {
    risk_score: 1.0,
    url: "https://www.wikipedia.org",
    tos_url: "https://foundation.wikimedia.org/wiki/Policy:Terms_of_Use",
    privacy_url: "https://foundation.wikimedia.org/wiki/Policy:Privacy_policy",
    tos_summary: "Wikipedia's Terms of Use ask you not to harass other editors, not to post copyrighted material without permission, and not to manipulate articles for pay. No account is required to read or edit most articles. Content you contribute is licensed under Creative Commons and becomes permanently public.",
    privacy_summary: "Wikipedia collects your IP address when you edit without an account and your username and edit history when you have one. No behavioral advertising is run on Wikipedia. Wikimedia does not sell user data and operates as a nonprofit funded entirely by donations.",
    tos_analysis: "This means Wikipedia's terms are designed to protect the encyclopedia, not to extract value from users. Clause 1 (Content license): anything you write or edit on Wikipedia is permanently licensed under Creative Commons BY-SA, meaning anyone can reuse it. Your contributions cannot be taken back. Clause 2 (Paid editing prohibition): writing Wikipedia articles for money without disclosure is prohibited and accounts doing so are banned. Clause 3 (No warranty): Wikipedia is provided as-is. The Wikimedia Foundation is not liable for inaccurate information or content changes made by other editors. Third-party sharing: none for advertising purposes. Basic server logs may be retained for security. A real-world scenario: you spend an afternoon writing a detailed Wikipedia article. It immediately becomes freely available to the entire internet under a Creative Commons license, permanently. Privacy advocate verdict: one of the most ethical terms of service on the internet.",
    privacy_analysis: "This means if you are not logged in, the only thing Wikipedia knows about you is your IP address. No red flags were identified. Logged-out browsing is entirely anonymous. Logged-in browsing reveals only your username and edit history, both of which are already public by design. Wikipedia does not run advertising and has no financial incentive to collect behavioral data. Third-party sharing: Wikimedia shares anonymized, aggregated traffic data with research partners only. No user-level data is sold. Privacy advocate verdict: reading Wikipedia is the closest thing to a fully private internet activity that a mainstream website offers."
  },
  "Signal" => {
    risk_score: 1.0,
    url: "https://signal.org",
    tos_url: "https://signal.org/legal/",
    privacy_url: "https://signal.org/legal/",
    tos_summary: "Signal's Terms of Service are minimal because the service is designed to hold as little data as possible. You must be 13 or older and agree not to use Signal for illegal activity. Signal can terminate accounts that abuse the platform but has almost no information about users to act on.",
    privacy_summary: "Signal knows your phone number, when you registered, and the last date you connected, and nothing else. Your messages, calls, contacts, and group memberships are end-to-end encrypted and inaccessible to Signal. When the US government subpoenaed Signal in 2021, the only data they could hand over was the registration date and last connection time.",
    tos_analysis: "This means Signal's terms barely exist because there is almost nothing for them to govern. Clause 1 (Phone number requirement): Signal requires a phone number to register. This is the only personal identifier they hold. Clause 2 (No data portability): if you change devices without a backup, your message history is gone. Signal cannot recover it because they never had it. Clause 3 (Abuse limitations): Signal can ban accounts that send spam, but the ban applies only to the phone number. Third-party sharing: none. Signal is a nonprofit and has no advertising business. A real-world scenario: law enforcement demands Signal hand over a user's messages. Signal hands over the registration date and last connection time. That is all they have. Privacy advocate verdict: the gold standard for private communication.",
    privacy_analysis: "This means a Signal data breach would expose essentially nothing about you. No red flags were identified. The architecture enforces privacy by design: even Signal engineers cannot read your messages. Sealed Sender technology means Signal cannot see who is messaging whom. Disappearing messages can be set to auto-delete, leaving no trace on either device. Third-party sharing: zero. Signal has no advertising partnerships, no data brokers, and no revenue from user data. Privacy advocate verdict: use Signal for anything you would not want read aloud in a courtroom."
  },
  "ProtonMail" => {
    risk_score: 1.0,
    url: "https://proton.me",
    tos_url: "https://proton.me/legal/terms",
    privacy_url: "https://proton.me/legal/privacy",
    tos_summary: "Proton's Terms of Service are straightforward: use the service lawfully, do not send spam, and do not abuse other users. Free accounts have storage limits and Proton can suspend accounts that violate the terms. Swiss law governs all agreements, giving users stronger privacy protections than US or EU jurisdiction.",
    privacy_summary: "Proton Mail encrypts your emails end-to-end, meaning Proton cannot read your messages even if they wanted to. Your emails are stored encrypted on servers in Switzerland, which has among the strongest data protection laws in the world. Proton does not run advertising and does not sell user data.",
    tos_analysis: "This means Proton's terms prioritize your rights rather than their own. Clause 1 (Swiss jurisdiction): disputes are resolved under Swiss law, which offers stronger protections against government surveillance requests than US law. Clause 2 (Account suspension): Proton can suspend accounts used for spam or illegal activity. Because messages are encrypted, they cannot actually read your emails to enforce this, so bans are based on complaints and metadata only. Clause 3 (Paid tier limits): free accounts have 1GB storage. Proton can change storage limits but cannot access your content regardless of tier. Third-party sharing: Proton shares only the legally required minimum in response to valid Swiss court orders. A real-world scenario: the FBI requests your email content from Proton. Proton hands over your account creation date and IP address. The emails themselves are unreadable. Privacy advocate verdict: the most trustworthy email provider available to regular consumers.",
    privacy_analysis: "This means your emails are private even from Proton itself. No red flags were identified. Zero-knowledge encryption means Proton holds the encrypted data but not the keys to decrypt it. IP addresses are anonymized after a short period unless you use Proton VPN, which eliminates them entirely. Proton has published every government data request it has received and what it was able to provide. Third-party sharing: zero for advertising. Legal requests receive the minimum information legally required under Swiss law. Privacy advocate verdict: if you care about email privacy, Proton is the right choice. It is the only major email provider that cannot hand over your message contents even under legal pressure."
  },
  "DuckDuckGo" => {
    risk_score: 1.0,
    url: "https://duckduckgo.com",
    tos_url: "https://duckduckgo.com/terms",
    privacy_url: "https://duckduckgo.com/privacy",
    tos_summary: "DuckDuckGo's Terms of Service are refreshingly short because there is almost nothing to agree to. No account is required, no content license exists, and there is no arbitration clause. The only restrictions are the obvious ones: don't use it for illegal activity and don't scrape it at scale.",
    privacy_summary: "DuckDuckGo does not know who you are, and by design, it never will. No search history is stored, no profile is built, and no data is sold to advertisers. Every search you run is treated as if it's the very first one you've ever made, because as far as DuckDuckGo is concerned, it is.",
    tos_analysis: "There are no concerning clauses to report because the terms do not grant DuckDuckGo any rights over your behavior or content. No content license (you don't post content). No arbitration clause (there's nothing to dispute). No account termination (there's no account). The only notable section is a standard prohibition against using the service to attack DuckDuckGo's own infrastructure. Third-party sharing: DuckDuckGo syndicates results from Bing, which means anonymized query terms are sent to Microsoft, but with no user identifiers attached. A real-world scenario: you search for something embarrassing. DuckDuckGo processes the query, returns results, and immediately forgets it happened. Privacy advocate verdict: this is what every search engine could look like if the business model didn't depend on harvesting your attention.",
    privacy_analysis: "This means that if someone hacked DuckDuckGo's servers tomorrow, they would find nothing linking any search to any person. No red flags were identified in this policy. The document is short precisely because the data practices are minimal: there is nothing to hide and nothing to explain away. Third-party note: the browser extension and mobile app include tracker-blocking features that actively prevent other companies from profiling you across the web. Third-party sharing: none for advertising. Privacy advocate verdict: use this as your default search engine. The search quality is comparable to Google for most queries and the privacy trade-off is zero."
  },
  "Mozilla" => {
    risk_score: 1.0,
    url: "https://www.mozilla.org",
    tos_url: "https://www.mozilla.org/en-US/about/legal/terms/firefox/",
    privacy_url: "https://www.mozilla.org/en-US/privacy/firefox/",
    tos_summary: "Firefox's Terms of Service cover the browser and Mozilla's associated services like Firefox Sync and Pocket. You agree not to use the browser for illegal purposes. Mozilla can update these terms at any time, though Firefox as a browser requires no account and can be used without agreeing to anything.",
    privacy_summary: "Firefox sends basic telemetry data to Mozilla by default, including your browser configuration and crash reports, but this can be turned off in settings. Mozilla does not sell user data and does not run behavioral advertising. Firefox is open source, meaning its data collection code can be independently verified by anyone.",
    tos_analysis: "This means Firefox's terms are about optional services, not the browser itself. Clause 1 (Firefox Sync): if you use Firefox Sync to store bookmarks and passwords, that data is stored on Mozilla's servers, encrypted with your password. Mozilla cannot read it. Clause 2 (Pocket): Firefox includes Pocket, which is owned by Mozilla. Reading activity in Pocket is collected and used for content recommendations. Clause 3 (Telemetry default): Firefox sends usage data to Mozilla by default, which can be disabled in Privacy settings at any time. Third-party sharing: none for advertising. Mozilla may share anonymized aggregate telemetry with research partners. A real-world scenario: you accept all Firefox defaults. Mozilla receives browser performance data and crash reports. No browsing history or personal data is included. Privacy advocate verdict: the most privacy-respecting major browser from the most trustworthy major browser company.",
    privacy_analysis: "This means Mozilla is collecting far less about you than Chrome or Edge by default, and you can turn off even that. No red flags were identified. Telemetry is opt-out but the data collected is genuinely anonymized and used for product improvement only. Firefox's Enhanced Tracking Protection blocks third-party trackers by default, reducing how much other companies can profile you. The open source codebase means privacy claims can be verified independently, unlike Chrome or Edge. Third-party sharing: none for commercial purposes. Privacy advocate verdict: use Firefox with uBlock Origin and you have one of the strongest default privacy setups available without any technical expertise."
  }
}.freeze
